### ISSUE TITLE
support ppc64le architecture

### ISSUE THREAD

**Issue by vaibhavsood** [Bonitasoft-Community/docker_bonita#7] opened 2017-09-27 11:09 UTC
Hi, wanted to check if this repo can be made multi-arch to support ppc64le, the changes to the Dockerfile will be minimal

I have gone through the arm issue #6 (and the last comment about no plans to support additional archs), however still want to confirm if that applies to ppc64le as well or if you would be willing to consider it? (i can work through docker's multi-arch steps to publish the ppc64le image on dockerhub, the changes should be simple enough), thanks!

**Comment by JeremJR** [comment] 2018-08-22 11:59
Hi @vaibhavsood ,
Sorry for the late response and thanks a lot for your interest.
As mentioned in https://github.com/Bonitasoft-Community/docker_bonita/issues/6 Bonitasoft do not officially support multiple architecture for Bonita at the moment. Anyway I've applied recommended changes in order to permit the build of arm64v8 images.
Regarding ppc64le, thanks to [Minicloud](https://minicloud.parqtec.unicamp.br/minicloud/) I've obtained a ppc64le VM but I'm not able to build bonita image yet. It seems stuck on "apt-get update". I don't know yet if it's an issue due to my environment, or the ubuntu ppc64le base image or a temporary issue on ubuntu mirrors for ppc64le?
On your side are you able to build bonita image on ppc64le?

**Comment by JeremJR** [comment] 2018-08-22 13:37
In fact it was an issue with my environment, it works if i use `--network=host` on my Minicloud VM.
So I've opened this PR https://github.com/docker-library/official-images/pull/4757 to permit the build of ppc64le images.

**Comment by JeremJR** [comment] 2018-08-23 09:03
Note that Minicloud answered me : "This problem is caused by openstack overhead, then to solve this you need set docker's MTU to 1450 MB following [this](https://rahulait.wordpress.com/2016/02/28/modifying-default-mtu-for-docker-containers/) tutorial."

The ppc64le image is docker pullable so I close this issue.

**Closed as completed** 2018-08-23 09:03 UTC
